spring:
  liquibase:
    change-log: classpath:db/master.yml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5435/sentryc_interview_test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver