databaseChangeLog:
  - changeSet:
      id: create-producers-table
      author: thinkitive
      changes:
        - createTable:
            tableName: producers
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    primaryKey: true
                    primaryKeyName: producersPK
              - column:
                  name: name
                  type: varchar(255)
              - column:
                  name: created_at
                  type: TIMESTAMP
                  constraints:
                    nullable: false
                    defaultValueComputed: 'now()'
  - changeSet:
      id: insert-producers-data
      author: thinkitive
      changes:
        - sqlFile:
            path: db/data/insert_producers_data.sql